### PR TITLE
Move updated tutorial to tutorials folder and copyedit

### PR DESCRIPTION
**Pull request by dymil**
The version in the repo root was slightly newer, hence moving it to the tutorials folder.

I also reran the notebook.

### CODE REVIEW

**Comment by vissarion** [comment]
Thanks for this PR! 
Please create two commits the one with the fixes and another one that moves the file because now it is not possible to see the changes you make in the files and thus review them.

**Comment by vissarion** [comment]
Thanks @dymil ! 

@hariszaf are you OK with the changes of this commit https://github.com/GeomScale/dingo/pull/38/commits/e35ef39da7acd0391f8d31c21bb342f96de06285 to the notebook ?

**Review by vissarion — APPROVED** [review]
LGTM, thanks!

**Comment by hariszaf** [comment]
Hi, apologies for the late reply. 
It's better not to have the community sampling at the tutorial for the moment, I agree. 
I hope we will have some insight on that the months to come. 
I am ok with the changes! Nice job! :100:

**Pull request merged**
